<a href="https://colab.research.google.com/github/husnain572/100-days-of-ML/blob/main/day_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU:{torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")

GPU is available
Using GPU:Tesla T4


### Creating a Tensor

In [3]:
a=torch.empty(2,3)
a

tensor([[0.0000e+00, 0.0000e+00, 7.7052e+31],
        [1.9447e+31, 2.1715e-18, 2.3081e-12]])

In [6]:
type(a)

torch.Tensor

In [7]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
torch.rand(2,4)

tensor([[0.1733, 0.5460, 0.5598, 0.8937],
        [0.9731, 0.8424, 0.5683, 0.4791]])

In [14]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [16]:
torch.tensor(
          [[1,2,3],
          [4,5,6]]
          )

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
print("using arange:\n",torch.arange(0,10,2))
print()
print("using linspace:\n",torch.linspace(0,10,3))
print()
print("using eye:\n",torch.eye(3))
print()
print("using full:\n",torch.full((3,3),5))

using arange:
 tensor([0, 2, 4, 6, 8])

using linspace:
 tensor([ 0.,  5., 10.])

using eye:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

using full:
 tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensor Shapes

In [31]:
x=torch.tensor([
                  [1,2,3],
                  [4,5,6]]
                )
x.shape

torch.Size([2, 3])

In [39]:
torch.empty_like(x)


tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6068937142572166454, 3473746687786889265, 6500156836907331886]])

In [41]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [42]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [54]:
torch.rand_like(x,dtype=torch.float64)

tensor([[0.1811, 0.5459, 0.3573],
        [0.2406, 0.5600, 0.6501]], dtype=torch.float64)

### Tensor Data Types

In [55]:
x.dtype

torch.int64

In [56]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [57]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [58]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


### Mathematical Operations

1. Scalar Operation

In [59]:
x=torch.rand(2,2)
x

tensor([[0.6211, 0.5530],
        [0.6896, 0.3687]])

In [ ]:
x+2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [ ]:
x*2

tensor([[1.4235, 1.5752],
        [0.8366, 1.8028]])

In [ ]:
x-2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [ ]:
x/2

tensor([[0.3559, 0.3938],
        [0.2092, 0.4507]])

In [ ]:
(x*100)//2

tensor([[35., 39.],
        [20., 45.]])

In [ ]:
((x*100)//2)%2

tensor([[1., 1.],
        [0., 1.]])

In [ ]:
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

2. Element wise operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [ ]:
a+b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [ ]:
a-b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [ ]:
a*b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [ ]:
a/b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [ ]:
a**b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [ ]:
a%b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [ ]:
c=torch.tensor([1,-2,3,-4])

In [ ]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

3. Reduction operation

In [66]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 6., 2.],
        [9., 5., 0.]])

In [ ]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([15.,  9.])

In [ ]:
# mean
torch.mean(e)


tensor(4.)

In [ ]:
# mean along col
torch.mean(e, dim=0)

tensor([4., 0., 8.])

In [ ]:
# median
torch.median(e)

tensor(0.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [ ]:
# product
torch.prod(e)

tensor(0.)

In [ ]:
# standard deviation
torch.std(e)

tensor(4.4272)

In [ ]:
# variance
torch.var(e)

tensor(19.6000)

In [77]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[0., 2., 1.],
        [2., 7., 9.]])

In [78]:
# argmax
torch.argmax(e)

tensor(5)

In [79]:
# argmin
torch.argmin(e)

tensor(0)

4. Matrix operations

In [80]:
f=torch.randint(size=(2,3), low=0,high=10)

g=torch.randint(size=(3,2), low=0,high=10)

print(f)
print()
print(g)

tensor([[2, 4, 6],
        [6, 8, 4]])

tensor([[9, 0],
        [7, 9],
        [2, 7]])


In [81]:
torch.matmul(f,g) # matrix multiplication


tensor([[ 58,  78],
        [118, 100]])

In [82]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

torch.dot(vector1, vector2)

tensor(11)

In [85]:
# transpose
torch.transpose(f, 0, 1)

tensor([[2, 6],
        [4, 8],
        [6, 4]])

In [86]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[0., 2., 4.],
        [4., 6., 2.],
        [1., 0., 5.]])

In [87]:
torch.det(h)

tensor(-60.)

In [88]:
# inverse
torch.inverse(h)

tensor([[-0.5000,  0.1667,  0.3333],
        [ 0.3000,  0.0667, -0.2667],
        [ 0.1000, -0.0333,  0.1333]])

5. Comparison operations

In [ ]:
i=torch.randint(size=(2,3), low=0, high=10)
j=torch.randint(size=(2,3), low=0, high=10)

print(i)
print()
print(j)

tensor([[0, 6, 9],
        [8, 9, 4]])

tensor([[3, 4, 6],
        [6, 5, 6]])


In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to
i>=j
# less than equal to
i<=j

tensor([[ True, False, False],
        [False, False,  True]])

6. Special functions

In [ ]:
k=torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[7., 4., 2.],
        [5., 4., 3.]])

In [ ]:
torch.log(k)

tensor([[1.9459, 1.3863, 0.6931],
        [1.6094, 1.3863, 1.0986]])

In [ ]:
torch.exp(k)

tensor([[1096.6332,   54.5981,    7.3891],
        [ 148.4132,   54.5981,   20.0855]])

In [ ]:
torch.sqrt(k)

tensor([[2.6458, 2.0000, 1.4142],
        [2.2361, 2.0000, 1.7321]])

In [ ]:
torch.sigmoid(k)

tensor([[0.9991, 0.9820, 0.8808],
        [0.9933, 0.9820, 0.9526]])

In [ ]:
torch.relu(k)

tensor([[7., 4., 2.],
        [5., 4., 3.]])

In [ ]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.8808, 0.5000, 0.2689],
        [0.1192, 0.5000, 0.7311]])

Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9781, 0.7847, 0.9775],
        [0.7762, 0.8201, 0.8237]])
tensor([[0.9848, 0.3829, 0.2058],
        [0.0796, 0.2178, 0.4349]])


In [ ]:
m.add_(n)

tensor([[1.9630, 1.1676, 1.1833],
        [0.8558, 1.0378, 1.2587]])

In [ ]:
m

tensor([[1.9630, 1.1676, 1.1833],
        [0.8558, 1.0378, 1.2587]])

In [ ]:
n

tensor([[0.9848, 0.3829, 0.2058],
        [0.0796, 0.2178, 0.4349]])

In [ ]:
torch.relu(m)

tensor([[1.9630, 1.1676, 1.1833],
        [0.8558, 1.0378, 1.2587]])

In [ ]:
m.relu_()

tensor([[1.9630, 1.1676, 1.1833],
        [0.8558, 1.0378, 1.2587]])

In [ ]:
m

tensor([[1.9630, 1.1676, 1.1833],
        [0.8558, 1.0378, 1.2587]])

Copying a Tensor

In [89]:
a = torch.rand(2,3)
a

tensor([[0.5934, 0.3124, 0.9431],
        [0.8519, 0.9815, 0.1132]])

In [90]:
b=a

In [91]:
a[0][0]=0

In [92]:
a

tensor([[0.0000, 0.3124, 0.9431],
        [0.8519, 0.9815, 0.1132]])

In [93]:
b

tensor([[0.0000, 0.3124, 0.9431],
        [0.8519, 0.9815, 0.1132]])

In [94]:
id(a)

135420064016064

In [95]:
id(b)

135420064016064

In [96]:
b = a.clone()
b

tensor([[0.0000, 0.3124, 0.9431],
        [0.8519, 0.9815, 0.1132]])

In [97]:
a

tensor([[0.0000, 0.3124, 0.9431],
        [0.8519, 0.9815, 0.1132]])

In [98]:
b

tensor([[0.0000, 0.3124, 0.9431],
        [0.8519, 0.9815, 0.1132]])

In [99]:
a[0][0] = 10

In [100]:
a

tensor([[10.0000,  0.3124,  0.9431],
        [ 0.8519,  0.9815,  0.1132]])

In [101]:
b

tensor([[0.0000, 0.3124, 0.9431],
        [0.8519, 0.9815, 0.1132]])

In [102]:
id(a)

135420064016064

In [103]:
id(b)

135420063810416

Tensor Operations on GPU

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
device=torch.device('cuda')


In [ ]:
torch.rand((2,3), device=device)

tensor([[0.2603, 0.5174, 0.5943],
        [0.4476, 0.2926, 0.7742]], device='cuda:0')

In [ ]:
a=torch.rand((2,3))
a

tensor([[0.3899, 0.0435, 0.9375],
        [0.5298, 0.0572, 0.0097]])

In [ ]:
b=a.to(device)

In [ ]:
b+a

Reshaping Tensors

In [ ]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b=torch.rand(2,3,4)
b

tensor([[[0.9166, 0.0010, 0.1156, 0.3913],
         [0.6676, 0.9470, 0.3880, 0.5697],
         [0.5609, 0.0604, 0.8581, 0.2050]],

        [[0.2350, 0.6653, 0.3711, 0.1311],
         [0.0418, 0.7340, 0.9080, 0.4933],
         [0.1327, 0.4329, 0.6502, 0.2001]]])

In [ ]:
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [ ]:
c=torch.rand(226,226,3) # typical image size

In [ ]:
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [ ]:
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

Numpy and PyTorch

In [ ]:
import numpy as np

In [ ]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b=a.numpy()
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])